//import 'package:clone_banco_inter/main.dart';

import 'item.dart';

const basePath = "assets/assets/images";

const apps = [
  /*
  AppItem(
    title: "Portifolio",
    published: false,
    deviceFrameIdentifier: "Medium",
    deviceFrameOrientation: "portrait",
    child: PortfolioApp(),
  ),
  AppItem(
    title: "Clone Banco Inter",
    published: false,
    deviceFrameIdentifier: "Medium",
    deviceFrameOrientation: "portrait",
    tags: [
      'RW',
      'RW2',
    ],
    child: BancoInterApp(),
  ),
  */
  Item(
    title: 'Ibmec/RioOpen Quiz 2023',
    published: false,
    obs: "Distribuído apenas durante os dias do evento",
    deviceFrameIdentifier: 'iPad',
    deviceFrameOrientation: 'portrait',
    tags: [
      'Tablet',
      'Flutter',
      'Dart',
      'Firebase'
    ],
    imagesUrls: [
      '$basePath/quiz/1.png',
      '$basePath/quiz/2.png',
      '$basePath/quiz/3.png',
      '$basePath/quiz/4.png',
      '$basePath/quiz/5.png',
      '$basePath/quiz/6.png',
    ],
  ),
  Item(
    title: 'CCAA Espaço Aluno',
    published: false,
    obs: 'Em desenvolvimento',
    tags: [
      'Celular',
      'Flutter',
      'Dart',
    ],
    deviceFrameIdentifier: 'Medium',
    imagesUrls: [
      '$basePath/espaco/1.jpg',
      '$basePath/espaco/2.jpg',
      '$basePath/espaco/3.jpg',
      '$basePath/espaco/4.jpg',
      '$basePath/espaco/5.jpg',
      '$basePath/espaco/6.jpg',
      '$basePath/espaco/7.jpg',
      '$basePath/espaco/8.jpg',
      '$basePath/espaco/9.jpg',
      '$basePath/espaco/10.jpg',
      '$basePath/espaco/11.jpg',
      '$basePath/espaco/12.jpg',
    ],
  ),
  Item(
    title: 'Sinta o Som',
    android: 'https://play.google.com/store/apps/details?id=br.com.kotrium.sintaosom',
    iOS: 'https://apps.apple.com/br/app/sinta-o-som/id1499651204',
    tags: [
      'Celular',
      'Flutter',
      'Dart',
      'Firebase',
      'HTML',
      'CSS'
    ],
    imagesUrls: [
      '$basePath/sintaosom/1.webp',
      '$basePath/sintaosom/2.webp',
      '$basePath/sintaosom/3.webp',
      '$basePath/sintaosom/4.webp',
      '$basePath/sintaosom/5.webp',
    ],
  ),
  Item(
    title: "CCAA Baby Class 1",
    android: 'https://play.google.com/store/apps/details?id=br.com.ccaa.pkum',
    iOS: 'https://apps.apple.com/br/app/ccaa-baby-class-1/id1502295293',
    deviceFrameIdentifier: 'Medium',
    deviceFrameOrientation: 'landscape',
    tags: [
      'Celular',
      'Tablet',
      'Unity',
      'C#',
    ],
    imagesUrls: [
      '$basePath/pk1/1.webp',
      '$basePath/pk1/2.webp',
      '$basePath/pk1/3.webp',
      '$basePath/pk1/4.webp',
      '$basePath/pk1/5.webp',
    ],
  ),
  Item(
    title: "CCAA Baby Class 2",
    android: 'https://play.google.com/store/apps/details?id=br.com.ccaa.pkdois',
    iOS: 'https://apps.apple.com/br/app/ccaa-baby-class-2/id1567437381',
    deviceFrameIdentifier: 'Medium',
    deviceFrameOrientation: 'landscape',
    tags: [
      'Celular',
      'Tablet',
      'Unity',
      'C#',
    ],
    imagesUrls: [
      '$basePath/pk2/1.webp',
      '$basePath/pk2/2.webp',
      '$basePath/pk2/3.webp',
      '$basePath/pk2/4.webp',
    ],
  ),
  Item(
    title: "CCAA Baby Class 3",
    android: 'https://play.google.com/store/apps/details?id=br.com.ccaa.pktres',
    iOS: 'https://apps.apple.com/br/app/ccaa-baby-class-3/id1538299542',
    deviceFrameIdentifier: 'Medium',
    deviceFrameOrientation: 'landscape',
    tags: [
      'Celular',
      'Tablet',
      'Unity',
      'C#',
    ],
    imagesUrls: [
      '$basePath/pk3/1.webp',
      '$basePath/pk3/2.webp',
      '$basePath/pk3/3.webp',
      '$basePath/pk3/4.webp',
    ],
  ),
  Item(
    title: "CCAA Baby Class 4",
    android: 'https://play.google.com/store/apps/details?id=br.com.ccaa.pkquatro',
    iOS: 'https://apps.apple.com/br/app/ccaa-baby-class-4/id1601871374',
    deviceFrameIdentifier: 'Medium',
    deviceFrameOrientation: 'landscape',
    tags: [
      'Celular',
      'Tablet',
      'Unity',
      'C#',
    ],
    imagesUrls: [
      '$basePath/pk4/1.webp',
      '$basePath/pk4/2.webp',
      '$basePath/pk4/3.webp',
      '$basePath/pk4/4.webp',
      '$basePath/pk4/5.webp',
    ],
  ),
  Item(
    title: "CCAA Baby Class 5",
    android: 'https://play.google.com/store/apps/details?id=br.com.ccaa.pkcinco',
    iOS: 'https://apps.apple.com/br/app/ccaa-baby-class-5/id1607390377',
    deviceFrameIdentifier: 'Medium',
    deviceFrameOrientation: 'landscape',
    tags: [
      'Celular',
      'Tablet',
      'Unity',
      'C#',
    ],
    imagesUrls: [
      '$basePath/pk5/1.webp',
      '$basePath/pk5/2.webp',
      '$basePath/pk5/3.webp',
      '$basePath/pk5/4.webp',
    ],
  ),
  Item(
    title: "CCAA Baby Class 6",
    android: 'https://play.google.com/store/apps/details?id=br.com.ccaa.pkseis',
    iOS: 'https://apps.apple.com/br/app/ccaa-baby-class-6/id1622237605',
    deviceFrameIdentifier: 'Medium',
    deviceFrameOrientation: 'landscape',
    tags: [
      'Celular',
      'Tablet',
      'Unity',
      'C#',
    ],
    imagesUrls: [
      '$basePath/pk6/1.webp',
      '$basePath/pk6/2.webp',
      '$basePath/pk6/3.webp',
      '$basePath/pk6/4.webp',
    ],
  ),
  Item(
    title: "CCAA Kids 1",
    android: 'https://play.google.com/store/apps/details?id=air.br.com.ccaa.kae1',
    iOS: 'https://apps.apple.com/br/app/ccaa-kids-1/id1254206862',
    deviceFrameIdentifier: 'Medium',
    deviceFrameOrientation: 'landscape',
    tags: [
      'Celular',
      'Tablet',
      'Unity',
      'C#',
    ],
    imagesUrls: [
      '$basePath/kae1/1.webp',
      '$basePath/kae1/2.webp',
    ],
  ),
  Item(
    title: "CCAA Kids 2",
    android: 'https://play.google.com/store/apps/details?id=br.com.ccaa.kaedois',
    iOS: 'https://apps.apple.com/br/app/ccaa-kids-2/id1239944595',
    deviceFrameIdentifier: 'Medium',
    deviceFrameOrientation: 'landscape',
    tags: [
      'Celular',
      'Tablet',
      'Unity',
      'C#',
    ],
    imagesUrls: [
      '$basePath/kae2/1.webp',
      '$basePath/kae2/2.webp',
      '$basePath/kae2/3.webp',
      '$basePath/kae2/4.webp',
      '$basePath/kae2/5.webp',
    ],
  ),
  Item(
    title: "CCAA Kids 3",
    android: 'https://play.google.com/store/apps/details?id=air.br.com.ccaa.kaetres',
    iOS: 'https://apps.apple.com/br/app/ccaa-kids-3/id1287519616',
    deviceFrameIdentifier: 'Medium',
    deviceFrameOrientation: 'landscape',
    tags: [
      'Celular',
      'Tablet',
      'Unity',
      'C#',
    ],
    imagesUrls: [
      '$basePath/kae3/1.webp',
      '$basePath/kae3/2.webp',
      '$basePath/kae3/3.webp',
      '$basePath/kae3/4.webp',
    ],
  ),
  Item(
    title: "CCAA Kids 4",
    android: 'https://play.google.com/store/apps/details?id=air.br.com.ccaa.kaequatro',
    iOS: 'https://apps.apple.com/br/app/ccaa-kids-4/id1242038251',
    deviceFrameIdentifier: 'Medium',
    deviceFrameOrientation: 'landscape',
    tags: [
      'Celular',
      'Tablet',
      'Unity',
      'C#',
    ],
    imagesUrls: [
      '$basePath/kae4/1.webp',
      '$basePath/kae4/2.webp',
    ],
  ),
  Item(
    title: "CCAA Kids 5",
    android: 'https://play.google.com/store/apps/details?id=air.br.com.ccaa.pckum',
    iOS: 'https://apps.apple.com/br/app/ccaa-kids-5/id1317074055',
    deviceFrameIdentifier: 'Medium',
    deviceFrameOrientation: 'landscape',
    tags: [
      'Celular',
      'Tablet',
      'Unity',
      'C#',
    ],
    imagesUrls: [
      '$basePath/pck1/1.webp',
      '$basePath/pck1/2.webp',
      '$basePath/pck1/3.webp',
      '$basePath/pck1/4.webp',
    ],
  ),
  Item(
    title: "CCAA Kids 6",
    android: 'https://play.google.com/store/apps/details?id=air.br.com.ccaa.pckdois',
    iOS: 'https://apps.apple.com/br/app/ccaa-kids-6/id1357328769',
    deviceFrameIdentifier: 'Medium',
    deviceFrameOrientation: 'landscape',
    tags: [
      'Celular',
      'Tablet',
      'Unity',
      'C#',
    ],
    imagesUrls: [
      '$basePath/pck2/1.webp',
      '$basePath/pck2/2.webp',
      '$basePath/pck2/3.webp',
      '$basePath/pck2/4.webp',
      '$basePath/pck2/5.webp',
      '$basePath/pck2/6.webp',
    ],
  ),
  Item(
    title: "CCAA Kids 7",
    android: 'https://play.google.com/store/apps/details?id=air.br.com.ccaa.pcbkum',
    iOS: 'https://apps.apple.com/br/app/ccaa-kids-7/id1407850969',
    deviceFrameIdentifier: 'Medium',
    deviceFrameOrientation: 'landscape',
    tags: [
      'Celular',
      'Tablet',
      'Unity',
      'C#',
    ],
    imagesUrls: [
      '$basePath/pcbk1/1.webp',
      '$basePath/pcbk1/2.webp',
      '$basePath/pcbk1/3.webp',
      '$basePath/pcbk1/4.webp',
    ],
  ),
  Item(
    title: "CCAA Kids 8",
    android: 'https://play.google.com/store/apps/details?id=air.br.com.ccaa.pcbkdois',
    iOS: 'https://apps.apple.com/br/app/ccaa-kids-8/id1390582125',
    deviceFrameIdentifier: 'Medium',
    deviceFrameOrientation: 'landscape',
    tags: [
      'Celular',
      'Tablet',
      'Unity',
      'C#',
    ],
    imagesUrls: [
      '$basePath/pcbk2/1.webp',
      '$basePath/pcbk2/2.webp',
      '$basePath/pcbk2/3.webp',
      '$basePath/pcbk2/4.webp',
      '$basePath/pcbk2/5.webp',
      '$basePath/pcbk2/6.webp',
    ],
  ),
  Item(
    title: "CCAA Preteen 1",
    android: 'https://play.google.com/store/apps/details?id=air.br.com.ccaa.pcptum',
    iOS: 'https://apps.apple.com/br/app/ccaa-preteen-1/id1437531458',
    deviceFrameIdentifier: 'Medium',
    deviceFrameOrientation: 'landscape',
    tags: [
      'Celular',
      'Tablet',
      'Unity',
      'C#',
    ],
    imagesUrls: [
      '$basePath/pcpt1/1.webp',
      '$basePath/pcpt1/2.webp',
      '$basePath/pcpt1/3.webp',
      '$basePath/pcpt1/4.webp',
      '$basePath/pcpt1/5.webp',
      '$basePath/pcpt1/6.webp',
    ],
  ),
  Item(
    title: "CCAA Preteen 2",
    android: 'https://play.google.com/store/apps/details?id=air.br.com.ccaa.pcptdois',
    iOS: 'https://apps.apple.com/br/app/ccaa-preteen-2/id1397414545',
    deviceFrameIdentifier: 'Medium',
    deviceFrameOrientation: 'landscape',
    tags: [
      'Celular',
      'Tablet',
      'Unity',
      'C#',
    ],
    imagesUrls: [
      '$basePath/pcpt2/1.webp',
      '$basePath/pcpt2/2.webp',
      '$basePath/pcpt2/3.webp',
      '$basePath/pcpt2/4.webp',
      '$basePath/pcpt2/5.webp',
      '$basePath/pcpt2/6.webp',
    ],
  ),
];
