import 'item.dart';

var apps = [
  Item(
    title: 'Ibmec/RioOpen Quiz 2023',
    published: false,
    obs: "Distribuído apenas durante os dias do evento",
    deviceFrameIdentifier: 'ios_tablet_ipad',
    deviceFrameOrientation: 'portrait',
    tags: [
      'Tablet',
      'Flutter',
      'Dart',
      'Firebase'
    ],
    imagesUrls: [
      'assets/assets/images/quiz/1.png',
      'assets/assets/images/quiz/2.png',
      'assets/assets/images/quiz/3.png',
      'assets/assets/images/quiz/4.png',
      'assets/assets/images/quiz/5.png',
      'assets/assets/images/quiz/6.png',
    ],
  ),
  Item(
    title: 'CCAA Espaço Aluno',
    published: false,
    obs: 'Em desenvolvimento',
    tags: [
      'Celular',
      'Flutter',
      'Dart',
    ],
    deviceFrameIdentifier: 'android_phone_medium',
    imagesUrls: [
      'assets/assets/images/espaco/1.jpg',
      'assets/assets/images/espaco/2.jpg',
      'assets/assets/images/espaco/3.jpg',
      'assets/assets/images/espaco/4.jpg',
      'assets/assets/images/espaco/5.jpg',
      'assets/assets/images/espaco/6.jpg',
      'assets/assets/images/espaco/7.jpg',
      'assets/assets/images/espaco/8.jpg',
      'assets/assets/images/espaco/9.jpg',
      'assets/assets/images/espaco/10.jpg',
      'assets/assets/images/espaco/11.jpg',
      'assets/assets/images/espaco/12.jpg',
    ],
  ),
  Item(
    title: 'Sinta o Som',
    android: 'https://play.google.com/store/apps/details?id=br.com.kotrium.sintaosom',
    iOS: 'https://apps.apple.com/br/app/sinta-o-som/id1499651204',
    tags: [
      'Celular',
      'Flutter',
      'Dart',
      'Firebase',
      'HTML',
      'CSS'
    ],
    imagesUrls: [
      'https://play-lh.googleusercontent.com/vz79SX4-PJfYuaEmKoXPdqwMT2B1QZ6inqdysvyPjoHT9P3nDYTzPT9RX0JFBUQhqS8Q=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/uJ_HecifWJ90nZValYKLR-o9_G6oJ10TxVAUSUm7R6C1FkRB1pdVPBWWCTbT0JgvzTw=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/up0OrajES1P7hL5_YHgCpD0IM1Fu4zg9kk-mam6LdOZMvN72zxC-qB-Rm8G4Uo1k35g0=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/Sj4zNY1wjQ15JwRXyfZ3gQbPnEZatULsfpXAK0IzCqYRaEEEkM_JD_yxZ9siwLojEvw=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/jyUhBYdcOtKx_eWRNA1Ko3_2OfRlUhSdKH3TB4QA1IlND2xAZJjguTKkWXQQD2vRKQ=w2560-h1440-rw',
    ],
  ),
  Item(
    title: "CCAA Baby Class 1",
    android: 'https://play.google.com/store/apps/details?id=br.com.ccaa.pkum',
    iOS: 'https://apps.apple.com/br/app/ccaa-baby-class-1/id1502295293',
    deviceFrameIdentifier: 'android_phone_medium',
    deviceFrameOrientation: 'landscape',
    tags: [
      'Celular',
      'Tablet',
      'Unity',
      'C#',
    ],
    imagesUrls: [
      'https://play-lh.googleusercontent.com/1c3QsXz3ty-MFI-kfyn28Pc1pUzUua2sSmGNl8zqFRJ8yzYr_hm-Fy_qOLAUPB6H2_w=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/dzWNHGosWIY2JsNcz4uh1UjnwYN676oUxSkUQAAAUhyITVcBUkFJqxC45pjRhZs12dA=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/aLxQfUbc_hlaqAQ2RcGlVd135yG1mCEtcD0jHTGYBeoSJTKdWE-P1eb6Zdg6b_2Zl7Tt=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/fXVjVlJ7q0uyOuU-9NzQ9n__ou0CnOdJ-hy_cFI2zuzTqMaQ854SuxZuKTJqfSGk2g=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/nPhVA1qsMFOuEicrIt2nmRXWUcjb6N7qFNe053v3SDFTi84-ykhWSmjMGTxPqZYgseA=w2560-h1440-rw',
    ],
  ),
  Item(
    title: "CCAA Baby Class 2",
    android: 'https://play.google.com/store/apps/details?id=br.com.ccaa.pkdois',
    iOS: 'https://apps.apple.com/br/app/ccaa-baby-class-2/id1567437381',
    deviceFrameIdentifier: 'android_phone_medium',
    deviceFrameOrientation: 'landscape',
    tags: [
      'Celular',
      'Tablet',
      'Unity',
      'C#',
    ],
    imagesUrls: [
      'https://play-lh.googleusercontent.com/QOIZyT6OnIzsIpzTmKuhQ3JfBgNr3N0bHcOCcpWNZcq178OIiiHqgZ-K6768371KkQ=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/kENCFp-loslGBpkLZtkmZvxWU4trPo5Kr3LjkCYiFc2VaZvR9jllhezLkxjrdv71pg=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/yJ69-OKvryqgeZvWTdtDXch1Mi1XgVxJv614oLNC4GpZBKAGEs1bUyNsixb2op8O_A=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/SHgnerBKmqKp4eDgHBIEqeXvERF3DYep7oCZ_c7TyxkC8zg_t0vofG6lV-XJ3-4R54E=w2560-h1440-rw',
    ],
  ),
  Item(
    title: "CCAA Baby Class 3",
    android: 'https://play.google.com/store/apps/details?id=br.com.ccaa.pktres',
    iOS: 'https://apps.apple.com/br/app/ccaa-baby-class-3/id1538299542',
    deviceFrameIdentifier: 'android_phone_medium',
    deviceFrameOrientation: 'landscape',
    tags: [
      'Celular',
      'Tablet',
      'Unity',
      'C#',
    ],
    imagesUrls: [
      'https://play-lh.googleusercontent.com/SfVohQDufWtgHMWqUXQzbodakAnzKsputtA9i7hSToI1bUGHu0UvmiVdGQfTllc6Lno=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/94Vb03-qI8aCuO8PD8_Wx49ooKenNmXcsHZBObDezXZ3dEPnGORkyhz0ire-Aj4I4N8=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/WFn8IfSqPAs_fQE2DWqDJ_g3l9lC1II14s4ON6xnZKyfu6Jm9Y3OtTIvLjmIzpwdbk4=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/rimgwr5SMKH_Qu_i57dhD9MJjfky9XDxc_jMTWokQLFzw5lUBkOe0yyG9S-MtETEcCS7=w2560-h1440-rw',
    ],
  ),
  Item(
    title: "CCAA Baby Class 4",
    android: 'https://play.google.com/store/apps/details?id=br.com.ccaa.pkquatro',
    iOS: 'https://apps.apple.com/br/app/ccaa-baby-class-4/id1601871374',
    deviceFrameIdentifier: 'android_phone_medium',
    deviceFrameOrientation: 'landscape',
    tags: [
      'Celular',
      'Tablet',
      'Unity',
      'C#',
    ],
    imagesUrls: [
      'https://play-lh.googleusercontent.com/DckNg4xdUqjyMQWtu49A7G_5fqaF1mZUaJp9z2ZJF9Omn7mMwnpAbdeuAi5GEON8-3A=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/_62MNjfK9k2z_5rf43FhKp0FiKD0GLm9XahfMfvmjCx1fCgag6RvxVYgyj6PXPdfJM8=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/cffRO6_BIzHfyMJbfkgQyESWZ4eC8Y9meQzMmB07OSTBg1iLSvQ44auoEsRYEmTXQk8=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/BkpvBV0y12wwM4qDSS_HmgTWT7izTFxICta8FeNM_I8SVBfpRCH2O6mqPJMgxFAy9Q=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/FvgW2gsL9VZTUABeFHzD5jX8VLA9a6zodPxyTj4l1njt05x8H3vznvQgyKE0vbswmU0=w2560-h1440-rw',
    ],
  ),
  Item(
    title: "CCAA Baby Class 5",
    android: 'https://play.google.com/store/apps/details?id=br.com.ccaa.pkcinco',
    iOS: 'https://apps.apple.com/br/app/ccaa-baby-class-5/id1607390377',
    deviceFrameIdentifier: 'android_phone_medium',
    deviceFrameOrientation: 'landscape',
    tags: [
      'Celular',
      'Tablet',
      'Unity',
      'C#',
    ],
    imagesUrls: [
      'https://play-lh.googleusercontent.com/fE6yqni9XpghrTwx1nLDCbuNEeZaC-D3I2GUPJoSaPneAOn1ZDMnqhjgDMEOc4kqx8w=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/zVEU6_1CDvMc-s1FCuKs0DFQnb_ReKDyrGaIbSY4ijM6RL1jZnr723y2gNj_TD2FOe3Y=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/WXBscqhRpiB4vjzseTFBS0hb_NL7vvltQHAnIl-ds3JPg5yqN5QroZNs1ykkxpL2AFV3=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/YdMTvGFFhqN12OcIaeQv-MCY2L1RDdy6ixYLUhxo6lkSjdk20fVpecaT-IPrBnIHuYE=w2560-h1440-rw',
    ],
  ),
  Item(
    title: "CCAA Baby Class 6",
    android: 'https://play.google.com/store/apps/details?id=br.com.ccaa.pkseis',
    iOS: 'https://apps.apple.com/br/app/ccaa-baby-class-6/id1622237605',
    deviceFrameIdentifier: 'android_phone_medium',
    deviceFrameOrientation: 'landscape',
    tags: [
      'Celular',
      'Tablet',
      'Unity',
      'C#',
    ],
    imagesUrls: [
      'https://play-lh.googleusercontent.com/5VUdfDRhmLQMWmzWc7XA7W1S29AttRcLpHQQiJp1khSwYYE3f-Ed-B1A9F9mrSUSxw=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/RjtmSKZArEJFIjrpM1EEWvMw-kSafcuJ9zznlGZ5B4rQBGaOva-i6A1MtBhVPU4RrSI=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/3tROwu0b8FqRIiIltcfgLkHsHa-YlfT0ODJKTg2Pk2RtOMkIPUR3aYguoNCbNr9Gmzo=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/incR2mtJ-TDSATe0W2HaY1F1eUid4XsR5YEuewXUfycgHec1FgHIECytElT8rCFFzek=w2560-h1440-rw',
    ],
  ),
  Item(
    title: "CCAA Kids 1",
    android: 'https://play.google.com/store/apps/details?id=air.br.com.ccaa.kae1',
    iOS: 'https://apps.apple.com/br/app/ccaa-kids-1/id1254206862',
    deviceFrameIdentifier: 'android_phone_medium',
    deviceFrameOrientation: 'landscape',
    tags: [
      'Celular',
      'Tablet',
      'Unity',
      'C#',
    ],
    imagesUrls: [
      'https://play-lh.googleusercontent.com/qN3EcYEA3P9pyTKHTTHMg52MxptD51HS_TrdFvpawDgRzG0MST6ISb-8HGDUlqHEgGM7=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/PMhXv5RZq7N1zsw7DeDJN13_bm7WpsEYgQ7stttTlASKHpJuR9zUsl4-PwfB8A62YTE=w2560-h1440-rw',
    ],
  ),
  Item(
    title: "CCAA Kids 2",
    android: 'https://play.google.com/store/apps/details?id=br.com.ccaa.kaedois',
    iOS: 'https://apps.apple.com/br/app/ccaa-kids-2/id1239944595',
    deviceFrameIdentifier: 'android_phone_medium',
    deviceFrameOrientation: 'landscape',
    tags: [
      'Celular',
      'Tablet',
      'Unity',
      'C#',
    ],
    imagesUrls: [
      'https://play-lh.googleusercontent.com/-qsTTPiv6VyYyZ4tvx22GX4-ZWrHEMDFc6YB-Qq0C8TUZ_ONDjaQtRVDatq6Av19E_lb=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/9DjV2F02D_wwM7BeUiHxE3YHwwP9CFhg-XeTxbU_OGR1sumfg_bNTMlRGOb3SbTNLw=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/bkNdpH3-Pujvf0vegG6LfVJw9mXNlu-c6g167YrkPhfsGg0RSq_L13OAzrENCCfO9MA=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/dCKtggr309wST4UYgnnnmDBop-ZBvZQJFZAr2jG59Hi95hu89Xf4euq8PDbWpCDMLCQ=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/HOOJBoso911lAN1UZZQoGT1NOqBG997i8WUrMMSrfo0HMUMAssFv-9upElWqu_OGlKM=w2560-h1440-rw',
    ],
  ),
  Item(
    title: "CCAA Kids 3",
    android: 'https://play.google.com/store/apps/details?id=air.br.com.ccaa.kaetres',
    iOS: 'https://apps.apple.com/br/app/ccaa-kids-3/id1287519616',
    deviceFrameIdentifier: 'android_phone_medium',
    deviceFrameOrientation: 'landscape',
    tags: [
      'Celular',
      'Tablet',
      'Unity',
      'C#',
    ],
    imagesUrls: [
      'https://play-lh.googleusercontent.com/RgZFQ4Q9QT0PP-2AaIrSLk1NHCy6cBSOrZff18k44MHhJc8w_9_49HxCMWvtx_YMRKU=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/mDce9ojMWLahk3j5rNY_3sk6tCOBFgRU2zKEe-islaWP2Yx8JTIaFTosbANqGLCAsh1H=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/GsbebLcxXWjT1seemtlG_JGewC8cg_r9jXs1-shM3jSzdIlf5ZxkEdhvt0NK7rznaA=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/I3QUqijZiMKrezh1FZw9DBFYf_8utEu4-bvmskSP9QPZO6dPMz5IdKqV9T6w20UCFg=w2560-h1440-rw',
    ],
  ),
  Item(
    title: "CCAA Kids 4",
    android: 'https://play.google.com/store/apps/details?id=air.br.com.ccaa.kaequatro',
    iOS: 'https://apps.apple.com/br/app/ccaa-kids-4/id1242038251',
    deviceFrameIdentifier: 'android_phone_medium',
    deviceFrameOrientation: 'landscape',
    tags: [
      'Celular',
      'Tablet',
      'Unity',
      'C#',
    ],
    imagesUrls: [
      'https://play-lh.googleusercontent.com/kebJbXaYSIKQz-9Ng6N2AK3viYWbgDwADuHWrv7Snm6iGKrZzmfZLiyuF-AyKqVXhEc=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/fakC1IMGofmp9iq11NBl0NZ5RAFtHlKGxgL91yDQXEY20cUeZpeP2QaJ1vrXWlYAyWv9=w2560-h1440-rw',
    ],
  ),
  Item(
    title: "CCAA Kids 5",
    android: 'https://play.google.com/store/apps/details?id=air.br.com.ccaa.pckum',
    iOS: 'https://apps.apple.com/br/app/ccaa-kids-5/id1317074055',
    deviceFrameIdentifier: 'android_phone_medium',
    deviceFrameOrientation: 'landscape',
    tags: [
      'Celular',
      'Tablet',
      'Unity',
      'C#',
    ],
    imagesUrls: [
      'https://play-lh.googleusercontent.com/EV3WkjG4xytq9DLfIGnQjH2HqgE0zniQ9KRO0C8LY3AxPFDppcNM-jYTgwso-1mxdVs=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/HGmrYtwz8no8HB_eTW0LJokANrYMm6YbmcafhmxReZDUF034prTqER27smpnf2La6eg=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/M4q4Z1RKrPdRNaQmYKDtVaiv24DkCyuXzmRBBs5z2gzSMVijBgdXAIJ4bqsK_WzeUg=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/g6G6QPAkxtW_X3CJSPHBEPDjICbaxhTa_wib_Hj41Ne4mEAEiRdjvI3EzUujqpVAdyA=w2560-h1440-rw',
    ],
  ),
  Item(
    title: "CCAA Kids 6",
    android: 'https://play.google.com/store/apps/details?id=air.br.com.ccaa.pckdois',
    iOS: 'https://apps.apple.com/br/app/ccaa-kids-6/id1357328769',
    deviceFrameIdentifier: 'android_phone_medium',
    deviceFrameOrientation: 'landscape',
    tags: [
      'Celular',
      'Tablet',
      'Unity',
      'C#',
    ],
    imagesUrls: [
      'https://play-lh.googleusercontent.com/FmGJ63IZniudlDGUGLB1YB7q0W56QDqO03btqqQSLX2BCENJjwXuJxH_MYECvc9Yxg=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/11BAN4cHgWWt1TAJmDPEwLiciu9dT5xQuwdLESgRoKZqUNB1PBhxipZYqLkzm2n1hw=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/wKGLKlIvBg3flMUY_D6cvzUQN6gmuVgPxS1uK5qeaKXbnV60Mxn_MTdZ-q0gdkqZCg=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/OhVDt_XlSxzkweBX209r5ZYtDWVWG8AVB_-yvFQ_4GC5soeUByrtjdBBQU3sYATsU1u9=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/atsdVxo6INHA_9HYsacp8nxNDX3P3bHCPNcMBmVn-VStC_nbwAnuEKh4Gv7a_kNMnyU=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/PlTnSvY7mk16LWa7QKlD-jyT-5PnB2MWFKGHSHfEx--AGOS3vTa9FeHOYSSvyFa4-fHF=w2560-h1440-rw',
    ],
  ),
  Item(
    title: "CCAA Kids 7",
    android: 'https://play.google.com/store/apps/details?id=air.br.com.ccaa.pcbkum',
    iOS: 'https://apps.apple.com/br/app/ccaa-kids-7/id1407850969',
    deviceFrameIdentifier: 'android_phone_medium',
    deviceFrameOrientation: 'landscape',
    tags: [
      'Celular',
      'Tablet',
      'Unity',
      'C#',
    ],
    imagesUrls: [
      'https://play-lh.googleusercontent.com/tMy0uKhVFTQQLs0Y49JnIDO0T7axAdUBn-MnmJLOGS-qG9IFduI-ZmeeAN9zzn3S8fs=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/MceKfnQRv9vnkWgz-KBQTr9mCkhzCnMYClR7T_Ui_P1eeyKnwTKiwMeLfZD4VfO77C0=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/d6hd0xjPtcRlKINy1yKadPUKlraiqVVLFrA1RUD9igGmcJNMqp6KAeOTcOFMLUpRIRA=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/iVma88pEB-kySG0YjMl03tDjcEaw5a3wmk2FtPRXdew87YLkJscCjSX8T3L5ycyOdQE=w2560-h1440-rw',
    ],
  ),
  Item(
    title: "CCAA Kids 8",
    android: 'https://play.google.com/store/apps/details?id=air.br.com.ccaa.pcbkdois',
    iOS: 'https://apps.apple.com/br/app/ccaa-kids-8/id1390582125',
    deviceFrameIdentifier: 'android_phone_medium',
    deviceFrameOrientation: 'landscape',
    tags: [
      'Celular',
      'Tablet',
      'Unity',
      'C#',
    ],
    imagesUrls: [
      'https://play-lh.googleusercontent.com/PebT6NVm9IWeRVw4X9SuBmdRuDTmhUZ6OP0R65pPQFcgLOtqcVTIdNpchgOhvoNvaz_L=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/xyDRZKn6n5cenq3uow8djgYkdmt3J3H2IeNt5MxQD2I4TGqjTGgS4yBBukOy3hLjzjM=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/dWJRiXJM6XDuF1_-wFcRQaWRXpq6tqBsT4pZnpPxPsc2S_DUGFcM1rvUM1nuui-t80o=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/D9qrho1kjoU1WiSJ6M0HS1EkYBeHQRj966-EPYUEgVWTzQvv2bRprIElJnC8KrU2-uU=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/3YVG62xbTrgyeG8kKE9-cW-e-LQip_u5T-9Ad6w03X5PG7uwEDvnLXfYqsm58rn8bRkX=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/CGO2zCqUIKg9EO1KzyZpeFQCnzNRM6QAs3ImodwjzAjdb3MaTtfVygxCqkSRaRwayA=w2560-h1440-rw',
    ],
  ),
  Item(
    title: "CCAA Preteen 1",
    android: 'https://play.google.com/store/apps/details?id=air.br.com.ccaa.pcptum',
    iOS: 'https://apps.apple.com/br/app/ccaa-preteen-1/id1437531458',
    deviceFrameIdentifier: 'android_phone_medium',
    deviceFrameOrientation: 'landscape',
    tags: [
      'Celular',
      'Tablet',
      'Unity',
      'C#',
    ],
    imagesUrls: [
      'https://play-lh.googleusercontent.com/Qbu9XPtP-P6eqPpnLZ3FcSgBaJrSWH0yH5IBFau7d9hUksVOXnbpYkdsviC6cZ8ck-E=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/DnpuxnoCKlM8UCAHvDJ3Jjs1gKcFEmZ92AgZGonorHVof2AZMhC7REG9OVmGNHwS4Bc=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/e2IwjRo7ePzYfwsx2OEl0-bx_cGiJQ0OXQqUBz6NZ1bWgSqqJQBQngsxeUefuyuY0w=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/UHRwhuogX-GCRTS5mPr7c6yN2LLigU7j46181mh77ZYoiXGCEm1EPcIV_J9tkEEq_Tg=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/H7jykFCb0Ot9a86VGQdxisiMS7Dlc3ZY6MeQCNGTMJKs-MPFKN4lpTFg_uWpSY0evtCK=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/MOo-9y-8gJS2aLQVlWsQ5RpWWF7VRLuRKF9VBQ8oDmvdpo82Cb5WfbEDq-dYpISmtg=w2560-h1440-rw',
    ],
  ),
  Item(
    title: "CCAA Preteen 2",
    android: 'https://play.google.com/store/apps/details?id=air.br.com.ccaa.pcptdois',
    iOS: 'https://apps.apple.com/br/app/ccaa-preteen-2/id1397414545',
    deviceFrameIdentifier: 'android_phone_medium',
    deviceFrameOrientation: 'landscape',
    tags: [
      'Celular',
      'Tablet',
      'Unity',
      'C#',
    ],
    imagesUrls: [
      'https://play-lh.googleusercontent.com/VIZdWeH4NHVJEzGC-J2yW3m6ctQreYTMBzOD8hPcOjvkSB5FcCpCnICfdmi1WLBmbg=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/jaoh6wLkQdfMRg31aUcpLsrt3kW4sk-_ePeZHURyxuFdOQthKEbPajIrD0v-jHiW0O-x=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/JE_QZYrO8ywScXeE5TFi8dLFZzQVqO62x44Xntp46rvEIC7jHcAKNPWsIhUEr_913lkl=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/GMaAx2bxeuTgH1CdisVCda8PKx-NTB-i7aBeVHejIj8FDwekUAWcwT0SgHbYMSb8HQ=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/9D9ISSpWOLr5h1df_-QSYYgt13avl90V5Jkx9IkpVmXkmxF-Ac7velLdZ2PgVJdNVn8=w2560-h1440-rw',
      'https://play-lh.googleusercontent.com/HZ605rLKoF0EEblvP31MbbjdQyfDIxJ6wj25F94XQrrjkDVWsGNDjypgvNkK_EqyeQ=w2560-h1440-rw',
    ],
  ),
];
